name: Build and Push to ECR

on:
  #push:
    #branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: gitaction

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::138645654058:role/ecr-push-role
          aws-region: ap-south-1

      - name: Ensure ECR repo exists and login
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY="$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
          aws ecr describe-repositories --repository-names "${{ env.ECR_REPOSITORY }}" || \
            aws ecr create-repository --repository-name "${{ env.ECR_REPOSITORY }}"
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
            docker login --username AWS --password-stdin "$ECR_REGISTRY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

       # 🔑  Create the tag variable
      - name: Compute image tag
        id: vars
        run: |
         
          TAG="v1.0.${{ github.run_number }}"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT



      # 🐳 Build and push image with the new tag

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Show pushed image
        run: |
          echo "Pushed: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
